export { forgotPassword } from './auth/forgotPassword'
export { cookieOptions, login } from './auth/login'
export { logout } from './auth/logout'
export { register } from './auth/register'
export { resetPassword } from './auth/resetPassword'
export { sendVerifyAccountEmail } from './auth/sendVerifyAccountEmail'
export { setNewEmailAddress } from './auth/setNewEmailAddress'
export { verifyAccount } from './auth/verifyAccount'
export { verifySession } from './auth/verifySession'
