export const MIN_PASSWORD_LENGTH = 8;
export const MIN_FIRST_NAME_LENGTH = 2;
export const MIN_LAST_NAME_LENGTH = 2;
export const MAX_FIRST_NAME_LENGTH = 50;
export const MAX_LAST_NAME_LENGTH = 50;

export const MAX_ABOUT_ME_LENGTH = 1000;

export const MAX_WORK_TITLE_LENGTH = 50;
export const MIN_WORK_TITLE_LENGTH = 5;

export const MIN_TASK_TITLE_LENGTH = 5;
export const MAX_TASK_TITLE_LENGTH = 50;
export const MIN_TASK_DESCRIPTION_LENGTH = 100;
export const MAX_TASK_DESCRIPTION_LENGTH = 1000;
export const GET_ALL_TASKS_MAX_LIMIT = 200;

export const MIN_TASK_REPLY_DESCRIPTION_LENGTH = 150;
export const MAX_TASK_REPLY_DESCRIPTION_LENGTH = 1000;
export const GET_TASK_REPLIES_MAX_LIMIT = 50;

export const GET_CHATS_MAX_LIMIT = 100;
