export { login } from './auth/login'
export { register } from './auth/register'
export { verifyAccount } from './auth/verifyAccount'
export {setNewEmailAddress} from './auth/setNewEmailAddress'
export {sendVerificationEmail} from './auth/sendVerificationEmail'