/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export enum TaskStatus {
  Completed = "completed",
  InProgress = "in_progress",
  Open = "open",
}

export enum UserRole {
  Admin = "admin",
  Client = "client",
  Freelancer = "freelancer",
}

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Category {
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  name: string;
  parentId: number | null;
  updatedAt: Generated<Timestamp>;
}

export interface Task {
  categoryId: number;
  clientId: number;
  createdAt: Generated<Timestamp>;
  description: string;
  freelancerId: number | null;
  id: Generated<number>;
  price: number;
  status: Generated<TaskStatus>;
  subcategoryId: number | null;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface TaskFiles {
  createdAt: Generated<Timestamp>;
  fileId: string;
  fileName: string;
  fileUrl: string;
  id: Generated<number>;
  taskId: number;
  updatedAt: Generated<Timestamp>;
}

export interface TaskViews {
  id: Generated<number>;
  taskId: number;
  userId: number | null;
}

export interface Users {
  aboutMe: string | null;
  avatar: string | null;
  avatarId: string | null;
  createdAt: Generated<Timestamp>;
  email: string;
  firstName: string;
  id: Generated<number>;
  isBanned: Generated<boolean>;
  isVerified: Generated<boolean>;
  lastName: string;
  password: string;
  role: UserRole;
  updatedAt: Generated<Timestamp>;
}

export interface WorkImages {
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  imageId: string;
  imageUrl: string;
  updatedAt: Generated<Timestamp>;
  workId: number;
}

export interface Works {
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  title: string;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface DB {
  category: Category;
  task: Task;
  taskFiles: TaskFiles;
  taskViews: TaskViews;
  users: Users;
  workImages: WorkImages;
  works: Works;
}
